name: Draft release

on:
  push:
    branches:
      - main

jobs:
  build-release:
    name: Draft release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check-out
        uses: actions/checkout@v4
      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3.7.1
        with:
          github-token: ${{ secrets.GHCR_TOKEN }}
          version-file: './package.json,./package-lock.json'
      - name: Create release
        uses: actions/create-release@v1
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GHCR_TOKEN }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
          draft: true

